### ISSUE TITLE
Diseñar e implementar protocolo para I/O de datos en Arduino

### ISSUE THREAD

**Issue by Marco-GG** [Ezetowers/MLC#22]
Se debe diseñar e implementar un protocolo que permita:
- Enviar valores a configurar en los puertos que se usen de salida
- Obtener los valores leidos en los puertos ADC

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Imeplementar protocolo para I/O de datos en Arduino](https://trello.com/c/UlBYOapx/91-imeplementar-protocolo-para-i-o-de-datos-en-arduino)

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Imeplementar protocolo para I/O de datos en Arduino](https://trello.com/c/UlBYOapx/91-imeplementar-protocolo-para-i-o-de-datos-en-arduino)

**Comment by Marco-GG** [comment]
Closed due that the protocol is implemented and running.
