### ISSUE TITLE
Persistir configuración de Boards en DB

### ISSUE THREAD

**Issue by Marco-GG** [Ezetowers/MLC#52]
Se debe perisistir en la DB del experimento la configuración del board para un experimento. El diseño de las tablas debe tomar en cuenta las siguientes restricciones:

- Almacenar la configuración general de lecturas ("read count", "read delay", "report mode")
- Almacenar los puertos de I/O (puertos analógicos, digitalese y de pwm)
- Datos del tipo de conexión al board (por el momento es solo serial, pero hay que contemplar que se puede soportar ethernet)

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Persistir configuración de Boards en DB](https://trello.com/c/NMbGRnh1/102-persistir-configuracion-de-boards-en-db)

**Comment by Marco-GG** [comment]
El feature fue implementado y se encuentra funcional
