### ISSUE TITLE
Bug :: Data len overflow en actuates con muchas lecturas

### ISSUE THREAD

**Issue by Marco-GG** [Ezetowers/MLC#56]
Actualmente la longitud de la respuesta de un actuate está limitada a un byte, lo cual es insuficiente si se configuran muchas lecturas en un pin (sobre todo en uno analógico).

Se debe duplicar el tamaño del campo (i.e. establecerlo en 2 bytes) a fin de evitar este problema.

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data len overflow en actuates con muchas lecturas](https://trello.com/c/wBvSjgyk/99-data-len-overflow-en-actuates-con-muchas-lecturas)
