### ISSUE TITLE
Bug :: Script de problema no se recarga

### ISSUE THREAD

**Issue by Marco-GG** [Ezetowers/MLC#57]
Cuando se edita el script de pruebas desde la GUI y se realizan cambios en el mismo los cambios no son tomandos al momento de correr el test. La posible razón es que python no está realizando el import de la clase si esta ya fue cargada.

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Script de problema no se recarga](https://trello.com/c/NpMAGouk/98-script-de-problema-no-se-recarga)
