### ISSUE TITLE
Lograr que la configuración del protocolo no se persista entre Experimentos

### ISSUE THREAD

**Issue by Ezetowers** [Ezetowers/MLC#60]
Actualmente la configuración de un protocolo se persiste de un experimento a otro. Es decir, lo que se configura en uno, termina apareciendo en el siguiente que se abre. Se debe arreglar este comportamiento

**Comment by Ezetowers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lograr que la configuración del protocolo no se persista entre Experimentos](https://trello.com/c/Ij4LSX2K/105-lograr-que-la-configuracion-del-protocolo-no-se-persista-entre-experimentos)

**Comment by Marco-GG** [comment]
Fixed on commit [https://github.com/Ezetowers/MLC/commit/dd0e357206bbcf410c3dfa90c45fe371147839f7](dd0e357)
